"""add refresh token fields to user

Revision ID: 830442c7bc12
Revises: c734044b6607
Create Date: 2026-08-03 23:42:08.718935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830442c7bc12'
down_revision: Union[str, Sequence[str], None] = 'c734044b6607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('refresh_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token_expiry')
    op.drop_column('user', 'refresh_token')
    # ### end Alembic commands ###
